<?php
// For use by Laminas\Loader\ClassMapAutoloader if not using Composer autoloading.
// See Module.php file in jim-moser\zf2-validators-empty-or-plugin package.
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'JimMoser\Validator\EmptyValidator' => __DIR__ . '/src/EmptyValidator.php',
    'JimMoser\Validator\VerboseOrChain' => __DIR__ . '/src/VerboseOrChain.php',
    'JimMoser\Validator\OrChain'        => __DIR__ . '/src/OrChain.php',
);
